apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{cookiecutter.pkg_name}}
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{cookiecutter.pkg_name}}
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: web
        image: postgres:9.6.15-alpine
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: app
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: app
