apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{cookiecutter.pkg_name}}
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{cookiecutter.pkg_name}}
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:alpine
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: celery
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        - name: RABBITMQ_DEFAULT_VHOST
          value: celery
